config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to: 'todos#index'

  get 'todos/list'

  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'

  post 'todos/:id/complete', to: 'todos#complete', as: 'todo_completed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.update_attribute :completed, true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "todos/parcial" %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>

</html>

app/views/todos/_parcial.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Tareas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link">
      <%=link_to "Index", todos_path %>
      </li>
      <li class="nav-item nav-link">
        <%=link_to "Listado", todos_list_path %>
      </li>

      <li class="nav-item nav-link">
        <%=link_to "Nueva Tarea", todos_new_path %>
      </li>

    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<%= form_with model: @todo, local: true do |todo| %>
 <%= todo.label :description, 'Ingrese la tarea' %>
 <%= todo.text_field :description %>
 <%= todo.label :completed, 'Tarea completada' %>
 <%= todo.check_box :completed %>
 <%= todo.submit "Crear" %>
<% end %>

app/views/todos/index.html.erb
    <% @todos.each do |check| %>
    <div class="card-header">
    <%=check.description %>
    <!-- <%=check.completed %> -->
    <%=link_to 'Ver', check %>
    <%=link_to 'Modificar', todo_edit_path(check) %>
    <%=link_to 'Borrar', check, method: :delete %>
    <%=link_to 'Completado', todo_completed_path(check), method: :post %>
    </div>
    <% end %>
<%=link_to 'Nueva tarea', todos_new_path %>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1> Tareas Imcompletas </h1>
      <% @todos.each do |check| %>
      <% if check.completed == false %>
      <%= link_to check.description, check %>
      <hr>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-6">
      <h1> Tareas completadas </h1>
      <% @todos.each do |check| %>
      <% if check.completed == true %>
      <%= link_to check.description, check %>
      <hr>
      <% end %>
      <% end %>
    </div>

</div>

app/views/todos/new.html.erb
<%= form_with model: @todo, local: true do |todo| %>
 <%= todo.label :description, 'Ingrese la tarea' %>
 <%= todo.text_field :description %>
 <%= todo.label :completed, 'Tarea completada' %>
 <%= todo.check_box :completed %>
 <%= todo.submit "Crear" %>
<% end %>

app/views/todos/show.html.erb
<%= @todo.description %>
<%= @todo.completed %>